config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/features'

  get 'welcome/faq'

  get 'welcome/pricing'

  resources :invoices

  root to: 'welcome#home'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
end

app/models/invoice_search.rb
class InvoiceSearch
  attr_reader :date_from, :date_to

  def initialize(params)
    params ||= {}
    @date_from = parse_date(params[:from], 7.days.ago.to_date.to_s)
    @date_to = parse_date(params[:to], Date.today.to_s)
  end

  def scope
    Invoice.where('date BETWEEN ? AND ?', @date_from, @date_to)
  end

  def parse_date(date_string,default)
  	Date.parse(date_string)
  	rescue ArgumentError, TypeError
  	default
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @search = InvoiceSearch.new(params[:date])
    @invoice = @search.scope

  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:date, :company, :tax, :salesperson)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def features
  end

  def faq
  end

  def pricing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :tax %><br>
    <%= f.text_field :tax %>
  </div>
  <div class="field">
    <%= f.label :salesperson %><br>
    <%= f.text_field :salesperson %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <h1>Listing Invoices</h1>
  <div class="pull-right range-query">
    <%= form_tag invoices_path, :method=> :get do %>
      <%= text_field_tag 'date[from]', @search.date_from %>
      <%= text_field_tag 'date[to]', @search.date_to %>
      <%= submit_tag "Search" %>
    <% end %>
  </div>
</div>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>Company</th>
          <th>Tax</th>
          <th>Salesperson</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @invoice.each do |invoice| %>
          <tr>
            <td><%= invoice.date.strftime("%Y-%m-%d") %></td>
            <td><%= invoice.company %></td>
            <td><%= invoice.tax %></td>
            <td><%= invoice.salesperson %></td>
            <td><%= link_to 'Show', invoice, class: "btn btn-mini btn-default" %></td>
            <td><%= link_to 'Edit', edit_invoice_path(invoice), class: "btn btn-mini btn-success" %></td>
            <td><%= link_to 'Destroy', invoice, method: :delete,class: "btn btn-mini btn-danger", data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>  

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Company:</strong>
  <%= @invoice.company %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @invoice.tax %>
</p>

<p>
  <strong>Salesperson:</strong>
  <%= @invoice.salesperson %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enterpriseape</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <ul class="nav nav-tabs">
	<li><%= link_to "Home",root_path %></li>
	<li><%= link_to "About Us",welcome_about_path %></li>
	<li><%= link_to "Contact",welcome_contact_path %></li>
	<li><%= link_to "Features",welcome_features_path %></li>
	<li><%= link_to "FAQs",welcome_faq_path %></li>
	<li><%= link_to "Invoices",invoices_path %></li>
	<li><%= link_to "Pricing",welcome_pricing_path %></li>
	<li><%= link_to "Login",root_path %></li>
  </ul>

<%= yield %>

</div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>TO see our review. Please check back our site</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>Find me in app/views/welcome/faq.html.erb</p>

app/views/welcome/features.html.erb
<h1>Welcome#features</h1>
<p>Find me in app/views/welcome/features.html.erb</p>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>

app/views/welcome/pricing.html.erb
<h1>Welcome#pricing</h1>
<p>Find me in app/views/welcome/pricing.html.erb</p>